#!/usr/bin/perl -w

use Diamond;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Diamond",
   ReceiveHandler => \&Receive);

$UNIVERSAL::diamond = Diamond->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::diamond->Process
    (Message => $args{Message});
}

$UNIVERSAL::diamond->Execute();
